# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish Docker image

on: 
  workflow_dispatch:
    inputs:
      checkout:
        type: string
        description: Branch to Checkout
        default: master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bitcoin

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.inputs.checkout }}
      
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create correct Image tag
        id: create-tag
        run: |
          IFS='/'
          read -a strarr <<< "${{ github.event.inputs.checkout }}"
          echo IMAGE_TAG=${strarr[1]} >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # tags: |
          #     type=semver,enable=true,pattern=v{{major}}.{{minor}},value=${{ github.event.inputs.checkout }}.99
          tags: |
            ${{ steps.create-tag.outputs.IMAGE_TAG }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # file: dev.Dockerfile
          build-args: |
            checkout=${{ github.event.inputs.checkout }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
#            linux/arm64
#            linux/arm/v7 
